services:
  PostgreSQL:
    image: postgres
    environment:
      - POSTGRES_USER=phatphuckdave
      - POSTGRES_PASSWORD=phatphuckdave765
      - POSTGRES_DB=phatphuckdave
    expose:
      - 5432
    command: -p 5432

  Server:
    image: 'phatphuckdave/musictribes'
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=phatphuckdave
      - POSTGRES_USER=phatphuckdave
      - POSTGRES_PASSWORD=phatphuckdave765
      - POSTGRES_HOST=PostgreSQL
      - POSTGRES_PORT=5432
    depends_on:
      - PostgreSQL

