# Generated by Django 4.0.2 on 2022-03-09 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('genre', models.CharField(max_length=32)),
                ('chieftain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tribes.cuser')),
            ],
        ),
        migrations.AddField(
            model_name='cuser',
            name='isMemberOf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tribes.tribe'),
        ),
    ]
