# Generated by Django 4.0.2 on 2022-03-09 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tribes', '0002_alter_cuser_options_alter_cuser_managers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CUser',
            new_name='User',
        ),
    ]
